# Generated by Django 4.0 on 2022-02-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='Notifications',
            new_name='notification_title',
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_description',
            field=models.TextField(null=True),
        ),
    ]
