# Generated by Django 4.0 on 2022-01-10 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickabook', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=500, null=True)),
                ('book_image', models.ImageField(null=True, upload_to='static/uploads')),
                ('book_pdf', models.FileField(null=True, upload_to='static/uploads')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pickabook.category')),
            ],
        ),
    ]
