# Generated by Django 4.0 on 2022-01-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickabook', '0004_remove_quotes_quote_title_quotes_quote_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
