# Generated by Django 4.0 on 2022-02-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickabook', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='author',
            field=models.ImageField(null=True, upload_to='static/uploads'),
        ),
    ]
