# Generated by Django 4.0 on 2022-02-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickabook', '0008_quotes_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
