# Generated by Django 4.0 on 2022-01-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writings',
            old_name='quote_author',
            new_name='name',
        ),
    ]
