# Generated by Django 4.0 on 2022-01-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_quote_author_writings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writings',
            name='image',
            field=models.ImageField(null=True, upload_to='static/uploads'),
        ),
    ]
