# Generated by Django 4.0 on 2022-01-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_writings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writings',
            name='image',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
    ]
